travis:
  secure:
    BINSTAR_TOKEN: Fb2KJFrYrsv+AaUnKVPfVcVxUNq4sutrPMweUqvUOZXoyp8xh/K0Les2DBTLbwNb6E+YZfjz2HKvSjqo2FskM8VPPmV8slRWdpFMIWC1tWHgK7KcfhVrsJEty/JYxzONIPFmzPobXF0QljkfxFgEbHlXVVFroJr/O5idWJUpY3k5BVboG9qxRRc0CiQyyI8tj0UnqRQQI6y4d0nokooEwDbpqGd5RiqwojscOv69AXkzeK+sn3aoCZrniyUxK7Wnu9R4mMKJUwKd5zdXvUVnbQ55Ol03DvJFZ+RhrworK8GOnE+MCsa1BItDT5/fG/vr62NYDio4+en5nWYWFRf0t1be6BcGzZpRCxugBTdur1mZJJqq+DjEcv7IGJiR0WweFOeaqxpn+626BITS1mjnNQyFK3jKd+aQWcm2u6uY1KYNVJ8H8Vy5VYcSXZwEcrD56t3gWooqB7Uzyx81BpPJJmcfedHyHngAkAa1zewTrTZB2107NrWTR9goBogmpGqIkf8TR0ln/4hnhwNkf/BKX8A4Qggj0QG7HecuYfB3wHO7TD7fKs2tqaA84yGhVubgwdPyMLlwHnyXmzDaCSd81JnBmY8HmJRTakgc9gtfx1wRlcHvTrpKle/VgAsxCxAVrq7RVfiuD7I8oCR+JHhMKoMW9xIGzwq5O3JWAqpQTrw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
